import {
  BLOCK_CONTENT_GROUP,
  BLOCK_NODE_GROUP,
  BLOCK_NODE_NAMES,
  EMOM_SLOT_NODE_NAME,
  EXERCISE_MENTION_NODE_NAME,
  INLINE_MENTION_GROUP,
  PRESCRIPTION_CHIP_NODE_NAME,
  SCHEME_MENTION_NODE_NAME,
  type BlockNodeName,
} from "../constants";

export const ROOT_BLOCK_NAMES: readonly BlockNodeName[] = BLOCK_NODE_NAMES;

export const INLINE_MENTION_NAMES = [
  EXERCISE_MENTION_NODE_NAME,
  SCHEME_MENTION_NODE_NAME,
  PRESCRIPTION_CHIP_NODE_NAME,
] as const;

export const EMOM_CHILD_NODE = EMOM_SLOT_NODE_NAME;

export const NODE_GROUPS = {
  block: BLOCK_NODE_GROUP,
  inlineMention: INLINE_MENTION_GROUP,
  blockContent: BLOCK_CONTENT_GROUP,
} as const;
