packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "prisma"
  - "sharp"
  - "unrs-resolver"

catalog:
  react: "^19.0.0"
  react-dom: "^19.0.0"
  next: "16.1.1"
  next-auth: "4.24.11"
  prisma: "6.1.0"
  "@prisma/client": "6.1.0"
  react-hook-form: "^7.54.2"
  "@hookform/resolvers": "^3.9.1"
  zod: "^3.24.1"
  "@tanstack/react-query": "^5.62.8"
  "@mui/material": "^7.3.6"
  "@mui/icons-material": "^7.3.6"
  "@mui/material-nextjs": "^7.3.6"
  "@emotion/cache": "^11.14.0"
  "@emotion/react": "^11.14.0"
  "@emotion/styled": "^11.14.0"
  clsx: "^2.1.1"
  class-variance-authority: "^0.7.1"
  lucide-react: "^0.469.0"
  typescript: "5.7.2"
  eslint: "^9.17.0"
  prettier: "3.5.3"
  prettier-plugin-sort-json: "^4.1.1"
  "@types/node": "^22.10.5"
  "@types/react": "^19.0.2"
  "@types/react-dom": "^19.0.2"
  bcryptjs: "^2.4.3"
  "@types/bcryptjs": "^2.4.6"
  "@vercel/blob": "^0.27.0"
  react-markdown: "^10.1.0"
