export const TEMPLATE_LIMITS = {
  MAX_NAME_LENGTH: 100,
  MAX_DESCRIPTION_LENGTH: 500,
  MAX_DAYS_PER_WEEK: 7,
  MAX_SESSIONS_PER_DAY: 10,
  MAX_BLOCKS_PER_SESSION: 20,
  MAX_SEGMENTS_PER_BLOCK: 20,
  MAX_SET_GROUPS_PER_SEGMENT: 20,
  MAX_ENTRIES_PER_SET_GROUP: 50,
} as const;
