export const BLOCK_KIND_CONSTANTS = {
  MAX_NAME_LENGTH: 100,
  MAX_DESCRIPTION_LENGTH: 500,
  MAX_ICON_KEY_LENGTH: 64,
  MAX_ANALYTICS_CATEGORY_LENGTH: 64,
  MIN_DEFAULT_WEIGHT: 1,
  MAX_DEFAULT_WEIGHT: 10,
} as const;
