import type { ExerciseCatalogEntry } from "../canonical-schema";

import { atomic, compound, placeholder } from "./catalog-exercises-helpers";

const BODYWEIGHT_EXERCISES: ExerciseCatalogEntry[] = [
  atomic("pull-up", "Pull-up", "BODYWEIGHT", "PULL", "pull-up", {
    demo: "https://example.com/demo/pull-up",
  }),
  atomic("strict-pull-up", "Strict Pull-up", "BODYWEIGHT", "PULL", "pull-up"),
  atomic("c2b-pull-up", "Chest-to-bar Pull-up", "BODYWEIGHT", "PULL", "pull-up"),
  atomic("bar-muscle-up", "Bar Muscle-up", "BODYWEIGHT", "PULL", "muscle-up"),
  atomic("toes-to-bar", "Toes-to-bar", "BODYWEIGHT", "CORE", "core"),
  atomic("knees-to-elbows", "Knees-to-elbows", "BODYWEIGHT", "CORE", "core"),
  atomic("strict-hspu", "Strict HSPU", "BODYWEIGHT", "PRESS", "handstand"),
  atomic("kipping-hspu", "Kipping HSPU", "BODYWEIGHT", "PRESS", "handstand"),
  atomic("hs-walk", "Handstand Walk", "BODYWEIGHT", "LOCOMOTION", "handstand"),
  atomic("pike-push-up", "Pike Push-up", "BODYWEIGHT", "PRESS", "push-up"),
  atomic("push-up", "Push-up", "BODYWEIGHT", "PRESS", "push-up"),
  atomic("clap-push-up", "Clap Push-up", "BODYWEIGHT", "PRESS", "push-up"),
  atomic("air-squat", "Air Squat", "BODYWEIGHT", "SQUAT", "squat"),
  atomic("pistol-squat", "Pistol Squat", "BODYWEIGHT", "SQUAT", "squat"),
  atomic("jump-squat", "Jump Squat", "BODYWEIGHT", "SQUAT", "squat"),
  atomic("burpee", "Burpee", "BODYWEIGHT", "LOCOMOTION", "burpee"),
  atomic("burpee-box-jump-over", "Burpee Box Jump Over", "BODYWEIGHT", "LOCOMOTION", "burpee"),
  atomic("box-jump", "Box Jump", "BODYWEIGHT", "LOCOMOTION", "box-jump"),
  atomic("box-step-up", "Box Step Up", "BODYWEIGHT", "LUNGE", "lunge"),
  atomic("walking-lunge", "Walking Lunge", "BODYWEIGHT", "LUNGE", "lunge"),
  atomic("sit-up", "Sit-up", "BODYWEIGHT", "CORE", "core"),
  atomic("v-up", "V-up", "BODYWEIGHT", "CORE", "core"),
  atomic("hollow-hold", "Hollow Hold", "BODYWEIGHT", "STATIC_HOLD", "core"),
  atomic("plank-hold", "Plank Hold", "BODYWEIGHT", "STATIC_HOLD", "core"),
  atomic("side-plank-hold", "Side Plank Hold", "BODYWEIGHT", "STATIC_HOLD", "core"),
  atomic("l-sit-hold", "L-sit Hold", "PARALLEL_BARS", "STATIC_HOLD", "core"),
  atomic("ring-row", "Ring Row", "RINGS", "PULL", "row"),
  atomic("strict-ring-pull-up", "Strict Ring Pull-up", "RINGS", "PULL", "pull-up"),
  atomic("ring-muscle-up", "Ring Muscle-up", "RINGS", "PULL", "muscle-up"),
  atomic("ring-dip", "Ring Dip", "RINGS", "PRESS", "dip"),
  atomic("bar-dip", "Bar Dip", "PARALLEL_BARS", "PRESS", "dip"),
  atomic("rope-climb", "Rope Climb", "BODYWEIGHT", "LOCOMOTION", "rope"),
  atomic("bear-crawl", "Bear Crawl", "BODYWEIGHT", "LOCOMOTION", "crawl"),
  atomic("crab-walk", "Crab Walk", "BODYWEIGHT", "LOCOMOTION", "crawl"),
  atomic("broad-jump", "Broad Jump", "BODYWEIGHT", "LOCOMOTION", "jump"),
  atomic("double-under", "Double Under", "JUMP_ROPE", "CARDIO_FLOW", "jump-rope"),
  atomic("single-under", "Single Under", "JUMP_ROPE", "CARDIO_FLOW", "jump-rope"),
  atomic("crossover-skip", "Crossover Skip", "JUMP_ROPE", "CARDIO_FLOW", "jump-rope"),
  atomic("run", "Run", "BODYWEIGHT", "LOCOMOTION", "run"),
  atomic("shuttle-run", "Shuttle Run", "BODYWEIGHT", "LOCOMOTION", "run"),
  atomic("sprint", "Sprint", "BODYWEIGHT", "LOCOMOTION", "run"),
  atomic("kipping-pull-up", "Kipping Pull-up", "BODYWEIGHT", "PULL", "pull-up"),
  atomic("butterfly-pull-up", "Butterfly Pull-up", "BODYWEIGHT", "PULL", "pull-up"),
  atomic("strict-toes-to-bar", "Strict Toes-to-bar", "BODYWEIGHT", "CORE", "core"),
  atomic("hollow-rock", "Hollow Rock", "BODYWEIGHT", "CORE", "core"),
  atomic("arch-hold", "Arch Hold", "BODYWEIGHT", "STATIC_HOLD", "core"),
  atomic("handstand-hold", "Handstand Hold", "BODYWEIGHT", "STATIC_HOLD", "handstand"),
];

const STATIC_AND_ROTATION_EXERCISES: ExerciseCatalogEntry[] = [
  atomic("russian-twist", "Russian Twist", "BODYWEIGHT", "ROTATIONAL", "rotation"),
  atomic("bb-rotation", "Barbell Rotation", "BARBELL", "ROTATIONAL", "rotation"),
  atomic("mb-rotation-throw", "Medball Rotation Throw", "MIXED", "ROTATIONAL", "rotation"),
  atomic("pallof-press", "Pallof Press", "BAND", "ROTATIONAL", "rotation"),
  atomic("windshield-wiper", "Windshield Wiper", "BODYWEIGHT", "ROTATIONAL", "rotation"),
  atomic("back-extension", "Back Extension", "BODYWEIGHT", "EXTENSION", "back"),
  atomic("ghd-back-extension", "GHD Back Extension", "BODYWEIGHT", "EXTENSION", "back"),
  atomic("ghd-sit-up", "GHD Sit-up", "BODYWEIGHT", "CORE", "core"),
];

const COMPOUND_EXERCISES: ExerciseCatalogEntry[] = [
  compound(
    "thruster-pull-up",
    "Thruster + Pull-up Complex",
    "MIXED",
    "COMBINED_OLYMPIC",
    "thruster",
    "COMPOUND_PLUS",
  ),
  compound(
    "clean-jerk-complex",
    "Clean + Jerk Complex",
    "BARBELL",
    "COMBINED_OLYMPIC",
    "clean",
    "COMPOUND_PLUS",
  ),
  compound(
    "snatch-balance-complex",
    "Snatch + Balance Complex",
    "BARBELL",
    "COMBINED_OLYMPIC",
    "snatch",
    "COMPOUND_PLUS",
  ),
  compound(
    "db-press-push-press",
    "DB Press + Push Press",
    "DUMBBELL",
    "PRESS",
    "press",
    "COMPOUND_PLUS",
  ),
  compound(
    "strict-press-push-press",
    "Strict Press + Push Press",
    "BARBELL",
    "PRESS",
    "press",
    "COMPOUND_PLUS",
  ),
  compound(
    "row-burpee",
    "Row + Burpee Composite",
    "MIXED",
    "CARDIO_FLOW",
    "row",
    "COMPOSITE_NAMED",
  ),
  compound(
    "dt-complex",
    "DT (Deadlift + Hang Clean + Push Jerk)",
    "BARBELL",
    "COMBINED_OLYMPIC",
    "dt",
    "COMPOSITE_NAMED",
  ),
  compound(
    "grace-complex",
    "Grace (Clean and Jerk × 30)",
    "BARBELL",
    "COMBINED_OLYMPIC",
    "grace",
    "COMPOSITE_NAMED",
  ),
  compound(
    "fran-complex",
    "Fran (Thruster + Pull-up Couplet)",
    "MIXED",
    "COMBINED_OLYMPIC",
    "fran",
    "COMPOSITE_NAMED",
  ),
  compound(
    "pull-up-or-ring-row",
    "Pull-up OR Ring Row",
    "MIXED",
    "PULL",
    "pull-up",
    "ALTERNATIVE_OR",
  ),
  compound(
    "back-squat-or-goblet",
    "Back Squat OR Goblet Squat",
    "MIXED",
    "SQUAT",
    "squat",
    "ALTERNATIVE_OR",
  ),
];

const PLACEHOLDER_EXERCISES: ExerciseCatalogEntry[] = [
  placeholder("placeholder-biceps-triceps", "Placeholder Biceps / Triceps", "accessory"),
  placeholder("placeholder-coach-choice", "Placeholder Coach Choice", null),
  placeholder("placeholder-abs", "Placeholder Abs", "core"),
  placeholder("placeholder-shoulder-accessory", "Placeholder Shoulder Accessory", "shoulder"),
  placeholder("placeholder-warm-up", "Placeholder Warm Up", null),
];

export const BODYWEIGHT_AND_COMPOUND_EXERCISES: ExerciseCatalogEntry[] = [
  ...BODYWEIGHT_EXERCISES,
  ...STATIC_AND_ROTATION_EXERCISES,
  ...COMPOUND_EXERCISES,
  ...PLACEHOLDER_EXERCISES,
];
