import { exerciseCuid } from "../builder";

export const EX = {
  backSquat: exerciseCuid("Back Squat"),
  frontSquat: exerciseCuid("Front Squat"),
  overheadSquat: exerciseCuid("Overhead Squat"),
  pauseBackSquat: exerciseCuid("Pause Back Squat"),
  conventionalDeadlift: exerciseCuid("Conventional Deadlift"),
  sumoDeadlift: exerciseCuid("Sumo Deadlift"),
  romanianDeadlift: exerciseCuid("Romanian Deadlift"),
  benchPress: exerciseCuid("Bench Press"),
  inclineBenchPress: exerciseCuid("Incline Bench Press"),
  strictPress: exerciseCuid("Strict Press"),
  pushPress: exerciseCuid("Push Press"),
  pushJerk: exerciseCuid("Push Jerk"),
  splitJerk: exerciseCuid("Split Jerk"),
  pendlayRow: exerciseCuid("Pendlay Row"),
  bentOverRow: exerciseCuid("Bent Over Row"),
  bbSnatch: exerciseCuid("Barbell Snatch"),
  powerSnatch: exerciseCuid("Power Snatch"),
  hangSnatch: exerciseCuid("Hang Snatch"),
  bbClean: exerciseCuid("Barbell Clean"),
  powerClean: exerciseCuid("Power Clean"),
  hangClean: exerciseCuid("Hang Clean"),
  thruster: exerciseCuid("Thruster"),
  bbWalkingLunge: exerciseCuid("Barbell Walking Lunge"),
  bbStepUp: exerciseCuid("Barbell Step Up"),
  bbCurl: exerciseCuid("Barbell Curl"),
  dbBenchPress: exerciseCuid("DB Bench Press"),
  dbInclinePress: exerciseCuid("DB Incline Press"),
  dbShoulderPress: exerciseCuid("DB Shoulder Press"),
  dbStrictPress: exerciseCuid("DB Strict Press"),
  dbPushPress: exerciseCuid("DB Push Press"),
  dbRow: exerciseCuid("DB Row"),
  dbRenegadeRow: exerciseCuid("DB Renegade Row"),
  dbSnatch: exerciseCuid("DB Snatch"),
  dbCleanAndJerk: exerciseCuid("DB Clean and Jerk"),
  dbThruster: exerciseCuid("DB Thruster"),
  dbWalkingLunge: exerciseCuid("DB Walking Lunge"),
  dbBulgarianSplitSquat: exerciseCuid("DB Bulgarian Split Squat"),
  dbStepUp: exerciseCuid("DB Step Up"),
  dbGobletSquat: exerciseCuid("DB Goblet Squat"),
  dbCurl: exerciseCuid("DB Curl"),
  dbHammerCurl: exerciseCuid("DB Hammer Curl"),
  dbLateralRaise: exerciseCuid("DB Lateral Raise"),
  dbDeadlift: exerciseCuid("DB Deadlift"),
  kbSwing: exerciseCuid("KB Swing"),
  kbSnatch: exerciseCuid("KB Snatch"),
  kbClean: exerciseCuid("KB Clean"),
  kbPress: exerciseCuid("KB Press"),
  kbRow: exerciseCuid("KB Row"),
  kbGobletSquat: exerciseCuid("KB Goblet Squat"),
  kbFarmersCarry: exerciseCuid("KB Farmers Carry"),
  kbSuitcaseCarry: exerciseCuid("KB Suitcase Carry"),
  kbTurkishGetUp: exerciseCuid("KB Turkish Get Up"),
  pullUp: exerciseCuid("Pull-up"),
  strictPullUp: exerciseCuid("Strict Pull-up"),
  c2bPullUp: exerciseCuid("Chest-to-bar Pull-up"),
  barMuscleUp: exerciseCuid("Bar Muscle-up"),
  toesToBar: exerciseCuid("Toes-to-bar"),
  kneesToElbows: exerciseCuid("Knees-to-elbows"),
  strictHspu: exerciseCuid("Strict HSPU"),
  kippingHspu: exerciseCuid("Kipping HSPU"),
  hsWalk: exerciseCuid("Handstand Walk"),
  pikePushUp: exerciseCuid("Pike Push-up"),
  pushUp: exerciseCuid("Push-up"),
  airSquat: exerciseCuid("Air Squat"),
  pistolSquat: exerciseCuid("Pistol Squat"),
  jumpSquat: exerciseCuid("Jump Squat"),
  burpee: exerciseCuid("Burpee"),
  burpeeBoxJumpOver: exerciseCuid("Burpee Box Jump Over"),
  boxJump: exerciseCuid("Box Jump"),
  boxStepUp: exerciseCuid("Box Step Up"),
  walkingLunge: exerciseCuid("Walking Lunge"),
  sitUp: exerciseCuid("Sit-up"),
  vUp: exerciseCuid("V-up"),
  hollowHold: exerciseCuid("Hollow Hold"),
  plankHold: exerciseCuid("Plank Hold"),
  sidePlankHold: exerciseCuid("Side Plank Hold"),
  lSitHold: exerciseCuid("L-sit Hold"),
  ringRow: exerciseCuid("Ring Row"),
  strictRingPullUp: exerciseCuid("Strict Ring Pull-up"),
  ringMuscleUp: exerciseCuid("Ring Muscle-up"),
  ringDip: exerciseCuid("Ring Dip"),
  barDip: exerciseCuid("Bar Dip"),
  ropeClimb: exerciseCuid("Rope Climb"),
  doubleUnder: exerciseCuid("Double Under"),
  singleUnder: exerciseCuid("Single Under"),
  run: exerciseCuid("Run"),
  shuttleRun: exerciseCuid("Shuttle Run"),
  sprint: exerciseCuid("Sprint"),
  rowErg: exerciseCuid("Row Erg"),
  rowCal: exerciseCuid("Row Erg (calories)"),
  skiErg: exerciseCuid("Ski Erg"),
  skiCal: exerciseCuid("Ski Erg (calories)"),
  bikeErgCal: exerciseCuid("Assault Bike (calories)"),
  bikeErgMin: exerciseCuid("Assault Bike Minutes"),
  atlasStoneToShoulder: exerciseCuid("Atlas Stone to Shoulder"),
  atlasStoneOver: exerciseCuid("Atlas Stone Over"),
  yokeCarry: exerciseCuid("Yoke Carry"),
  sledPush: exerciseCuid("Sled Push"),
  sledPull: exerciseCuid("Sled Pull"),
  bandPullApart: exerciseCuid("Band Pull Apart"),
  bandRow: exerciseCuid("Band Row"),
  bandBicepCurl: exerciseCuid("Band Bicep Curl"),
  bandTricepPushdown: exerciseCuid("Band Tricep Pushdown"),
  boxPistol: exerciseCuid("Box Pistol Squat"),
  sofaStepUp: exerciseCuid("Sofa Step Up"),
  russianTwist: exerciseCuid("Russian Twist"),
  ghdSitUp: exerciseCuid("GHD Sit-up"),
  ghdBackExtension: exerciseCuid("GHD Back Extension"),
  thrusterPullUp: exerciseCuid("Thruster + Pull-up Complex"),
  cleanJerkComplex: exerciseCuid("Clean + Jerk Complex"),
  dbPressPushPress: exerciseCuid("DB Press + Push Press"),
  strictPressPushPress: exerciseCuid("Strict Press + Push Press"),
  dtComplex: exerciseCuid("DT (Deadlift + Hang Clean + Push Jerk)"),
  pullUpOrRingRow: exerciseCuid("Pull-up OR Ring Row"),
  backSquatOrGoblet: exerciseCuid("Back Squat OR Goblet Squat"),
  placeholderBicepsTriceps: exerciseCuid("Placeholder Biceps / Triceps"),
  placeholderCoachChoice: exerciseCuid("Placeholder Coach Choice"),
  placeholderAbs: exerciseCuid("Placeholder Abs"),
  placeholderShoulderAccessory: exerciseCuid("Placeholder Shoulder Accessory"),
  placeholderWarmUp: exerciseCuid("Placeholder Warm Up"),
} as const;

export const LBL = {
  restDay: "rest-day",
  main: "main",
  firstSession: "1st-session",
  secondSession: "2nd-session",
  strength: "strength",
  metcon: "metcon",
  conditioning: "conditioning",
  endurance: "endurance",
  pump: "pump",
  gymnastics: "gymnastics",
  skill: "skill",
  olympic: "olympic",
  accessory: "accessory",
  partner: "partner",
  strengthEndurance: "strength-endurance",
  easyPace: "easy-pace",
  warmUpFeet: "warm-up-feet",
  warmUpRun: "warm-up-run",
  core: "core",
  practice: "practice",
  coolDown: "cool-down",
  mobility: "mobility",
} as const;
