export const EXERCISE_LIBRARY_ITEM_CONSTANTS = {
  MAX_NAME_LENGTH: 200,
  MAX_DESCRIPTION_LENGTH: 2000,
  MAX_ALIAS_LENGTH: 100,
  MAX_ALIASES: 25,
  MAX_EQUIPMENT_TAG_LENGTH: 80,
  MAX_EQUIPMENT_TAGS: 20,
  MAX_BODY_PARTS: 13,
} as const;
