import { bodyweightExercise, cardioExercise, type ExerciseSeed } from "./helpers";

const cardioSection: ExerciseSeed[] = [
  cardioExercise({
    name: "400m Run",
    description: "Standard quarter-mile run, all-out or paced.",
    primaryMovement: "CARDIO_RUN",
    equipment: [],
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["QUADS", "CALVES", "POSTERIOR_CHAIN"],
    skillLevel: "BEGINNER",
    isBenchmark: true,
  }),
  cardioExercise({
    name: "800m Run",
    description: "Half-mile run, sustained pace effort.",
    primaryMovement: "CARDIO_RUN",
    equipment: [],
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["QUADS", "CALVES", "POSTERIOR_CHAIN"],
    skillLevel: "BEGINNER",
  }),
  cardioExercise({
    name: "1km Run",
    description: "One-kilometer run for pacing and aerobic work.",
    primaryMovement: "CARDIO_RUN",
    equipment: [],
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["QUADS", "CALVES", "POSTERIOR_CHAIN"],
    skillLevel: "BEGINNER",
  }),
  cardioExercise({
    name: "1mi Run",
    description: "Standard one-mile run, threshold or all-out effort.",
    primaryMovement: "CARDIO_RUN",
    equipment: [],
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["QUADS", "CALVES", "POSTERIOR_CHAIN"],
    skillLevel: "BEGINNER",
    isBenchmark: true,
  }),
  cardioExercise({
    name: "5k Run",
    description: "Five-kilometer run for endurance and tempo work.",
    primaryMovement: "CARDIO_RUN",
    equipment: [],
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["QUADS", "CALVES", "POSTERIOR_CHAIN"],
    skillLevel: "INTERMEDIATE",
  }),
  cardioExercise({
    name: "Row",
    nameAliases: ["Concept2 Row", "Erg Row"],
    description: "Concept2 rowing erg, drive with legs first, finish with arms.",
    primaryMovement: "CARDIO_ROW",
    equipment: ["rower"],
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["BACK", "POSTERIOR_CHAIN", "QUADS"],
    skillLevel: "BEGINNER",
    isBenchmark: true,
  }),
  cardioExercise({
    name: "Bike Erg",
    nameAliases: ["Concept2 Bike Erg"],
    description: "Concept2 bike erg, sustained or interval-based output.",
    primaryMovement: "CARDIO_BIKE",
    equipment: ["bike"],
    primaryBodyParts: ["QUADS", "FULL_BODY"],
    secondaryBodyParts: ["GLUTES", "CALVES"],
    skillLevel: "BEGINNER",
  }),
  cardioExercise({
    name: "Echo Bike",
    nameAliases: ["Assault Bike", "Air Bike"],
    description: "Fan bike with arm and leg drive, brutal high-output effort.",
    primaryMovement: "CARDIO_BIKE",
    equipment: ["bike"],
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["QUADS", "SHOULDERS"],
    skillLevel: "BEGINNER",
  }),
  cardioExercise({
    name: "Ski Erg",
    nameAliases: ["Concept2 SkiErg"],
    description: "SkiErg double-pole motion, hinge with full body engagement.",
    primaryMovement: "CARDIO_OTHER",
    equipment: ["ski-erg"],
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["BACK", "CORE", "POSTERIOR_CHAIN"],
    skillLevel: "BEGINNER",
  }),
  bodyweightExercise({
    name: "Double-under",
    nameAliases: ["DU"],
    description: "Jump rope passes twice under feet per single jump.",
    primaryMovement: "EXPLOSIVE",
    equipment: ["jump-rope"],
    primaryBodyParts: ["CALVES", "FULL_BODY"],
    secondaryBodyParts: ["SHOULDERS", "CORE"],
    skillLevel: "INTERMEDIATE",
    metrics: {
      canMeasureLoad: false,
      canMeasureReps: true,
      canMeasureDuration: true,
      canMeasureDistance: false,
      canMeasureCalories: false,
    },
    isBenchmark: true,
  }),
];

const miscExplosive: ExerciseSeed[] = [
  bodyweightExercise({
    name: "Single-under",
    nameAliases: ["SU"],
    description: "Standard jump rope, one pass per jump.",
    primaryMovement: "EXPLOSIVE",
    equipment: ["jump-rope"],
    primaryBodyParts: ["CALVES", "FULL_BODY"],
    secondaryBodyParts: ["SHOULDERS"],
    skillLevel: "BEGINNER",
    metrics: {
      canMeasureLoad: false,
      canMeasureReps: true,
      canMeasureDuration: true,
      canMeasureDistance: false,
      canMeasureCalories: false,
    },
  }),
  bodyweightExercise({
    name: "Box Step-up",
    description: "Step onto box with one leg, drive to standing on top.",
    primaryMovement: "LUNGE",
    equipment: ["box"],
    primaryBodyParts: ["QUADS", "GLUTES"],
    secondaryBodyParts: ["HAMSTRINGS", "CORE"],
    skillLevel: "BEGINNER",
  }),
  cardioExercise({
    name: "Sled Push",
    description: "Drive sled forward with full-body push, low body angle.",
    primaryMovement: "CARDIO_OTHER",
    equipment: ["sled"],
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["QUADS", "GLUTES", "CORE"],
    skillLevel: "BEGINNER",
  }),
  cardioExercise({
    name: "Sled Pull",
    description: "Pull sled with rope or harness, full hip extension on each step.",
    primaryMovement: "CARDIO_OTHER",
    equipment: ["sled"],
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["BACK", "POSTERIOR_CHAIN", "CORE"],
    skillLevel: "BEGINNER",
  }),
];

export const CARDIO_MISC_SEEDS: readonly ExerciseSeed[] = [...cardioSection, ...miscExplosive];
