import { bodyweightExercise, dumbbellExercise, type ExerciseSeed } from "./helpers";

const corePattern: ExerciseSeed[] = [
  bodyweightExercise({
    name: "Sit-up",
    description: "Lying on back, sit up touching feet or chest to knees.",
    primaryMovement: "CORE_FLEXION",
    primaryBodyParts: ["CORE"],
    skillLevel: "BEGINNER",
  }),
  {
    name: "GHD Sit-up",
    description: "Glute-ham developer sit-up, full hip extension to flexion.",
    primaryMovement: "CORE_FLEXION",
    nameAliases: ["GHD"],
    modality: "MACHINE",
    equipment: ["ghd"],
    primaryBodyParts: ["CORE"],
    secondaryBodyParts: ["HIPS"],
    skillLevel: "INTERMEDIATE",
    defaultMetrics: {
      canMeasureLoad: false,
      canMeasureReps: true,
      canMeasureDuration: false,
      canMeasureDistance: false,
      canMeasureCalories: false,
    },
    isBenchmark: false,
  },
  bodyweightExercise({
    name: "Toes-to-bar",
    nameAliases: ["T2B"],
    description: "Hanging from bar, kip toes to touch bar between hands.",
    primaryMovement: "CORE_FLEXION",
    equipment: ["pull-up bar"],
    primaryBodyParts: ["CORE"],
    secondaryBodyParts: ["BACK", "ARMS_BICEPS"],
    skillLevel: "INTERMEDIATE",
    isBenchmark: true,
  }),
  bodyweightExercise({
    name: "Knees-to-Elbows",
    nameAliases: ["K2E"],
    description: "Hanging from bar, raise knees to touch elbows.",
    primaryMovement: "CORE_FLEXION",
    equipment: ["pull-up bar"],
    primaryBodyParts: ["CORE"],
    secondaryBodyParts: ["BACK", "ARMS_BICEPS"],
    skillLevel: "INTERMEDIATE",
  }),
  bodyweightExercise({
    name: "Hollow Hold",
    description: "Lying on back, lift legs and shoulders, lower back pressed to floor.",
    primaryMovement: "CORE_ANTI",
    primaryBodyParts: ["CORE"],
    skillLevel: "BEGINNER",
    metrics: {
      canMeasureLoad: false,
      canMeasureReps: false,
      canMeasureDuration: true,
      canMeasureDistance: false,
      canMeasureCalories: false,
    },
  }),
  bodyweightExercise({
    name: "Plank",
    description: "Forearms or hands on ground, body in straight line, hold isometric.",
    primaryMovement: "CORE_ANTI",
    primaryBodyParts: ["CORE"],
    secondaryBodyParts: ["SHOULDERS"],
    skillLevel: "BEGINNER",
    metrics: {
      canMeasureLoad: false,
      canMeasureReps: false,
      canMeasureDuration: true,
      canMeasureDistance: false,
      canMeasureCalories: false,
    },
  }),
  dumbbellExercise({
    name: "Russian Twist",
    description: "Seated with feet off ground, rotate dumbbell side to side.",
    primaryMovement: "ROTATION",
    primaryBodyParts: ["CORE"],
    secondaryBodyParts: ["HIPS"],
    skillLevel: "BEGINNER",
  }),
  bodyweightExercise({
    name: "V-up",
    description: "Lying flat, simultaneously raise legs and torso to touch toes.",
    primaryMovement: "CORE_FLEXION",
    primaryBodyParts: ["CORE"],
    skillLevel: "INTERMEDIATE",
  }),
];

const gymnasticSkill: ExerciseSeed[] = [
  bodyweightExercise({
    name: "Handstand Hold",
    description: "Inverted vertical hold against wall or freestanding.",
    primaryMovement: "GYMNASTIC_HOLD",
    equipment: ["wall"],
    primaryBodyParts: ["SHOULDERS", "CORE"],
    secondaryBodyParts: ["ARMS_TRICEPS"],
    skillLevel: "INTERMEDIATE",
    metrics: {
      canMeasureLoad: false,
      canMeasureReps: false,
      canMeasureDuration: true,
      canMeasureDistance: false,
      canMeasureCalories: false,
    },
  }),
  bodyweightExercise({
    name: "Handstand Walk",
    nameAliases: ["HS Walk"],
    description: "Freestanding handstand with locomotion forward on hands.",
    primaryMovement: "GYMNASTIC_INVERTED",
    primaryBodyParts: ["SHOULDERS", "CORE"],
    secondaryBodyParts: ["ARMS_TRICEPS"],
    skillLevel: "ADVANCED",
    metrics: {
      canMeasureLoad: false,
      canMeasureReps: false,
      canMeasureDuration: false,
      canMeasureDistance: true,
      canMeasureCalories: false,
    },
  }),
  bodyweightExercise({
    name: "L-sit",
    description: "Support on parallettes or rings, legs extended parallel to floor.",
    primaryMovement: "GYMNASTIC_HOLD",
    primaryBodyParts: ["CORE", "SHOULDERS"],
    secondaryBodyParts: ["ARMS_TRICEPS", "QUADS"],
    skillLevel: "ADVANCED",
    metrics: {
      canMeasureLoad: false,
      canMeasureReps: false,
      canMeasureDuration: true,
      canMeasureDistance: false,
      canMeasureCalories: false,
    },
  }),
  bodyweightExercise({
    name: "Ring Dip",
    description: "Support on rings, lower with control, press to lockout.",
    primaryMovement: "PUSH_VERTICAL",
    equipment: ["rings"],
    primaryBodyParts: ["CHEST", "ARMS_TRICEPS"],
    secondaryBodyParts: ["SHOULDERS", "CORE"],
    skillLevel: "ADVANCED",
  }),
  bodyweightExercise({
    name: "Box Jump",
    description: "Jump onto box from standing, full hip extension at top.",
    primaryMovement: "EXPLOSIVE",
    equipment: ["box"],
    primaryBodyParts: ["QUADS", "GLUTES"],
    secondaryBodyParts: ["CALVES", "CORE"],
    skillLevel: "BEGINNER",
  }),
  bodyweightExercise({
    name: "Burpee",
    description: "Drop to ground, push-up, jump up with hands overhead.",
    primaryMovement: "COMBO",
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["CHEST", "QUADS", "CORE"],
    skillLevel: "BEGINNER",
    metrics: {
      canMeasureLoad: false,
      canMeasureReps: true,
      canMeasureDuration: true,
      canMeasureDistance: false,
      canMeasureCalories: false,
    },
    isBenchmark: true,
  }),
  bodyweightExercise({
    name: "Burpee Box Jump-over",
    description: "Burpee followed by jump or step over box, alternate sides.",
    primaryMovement: "COMBO",
    equipment: ["box"],
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["QUADS", "GLUTES"],
    skillLevel: "INTERMEDIATE",
  }),
  bodyweightExercise({
    name: "Rope Climb",
    description: "Climb rope using legs and arms, descend with control.",
    primaryMovement: "PULL_VERTICAL",
    equipment: ["rope"],
    primaryBodyParts: ["BACK", "ARMS_BICEPS"],
    secondaryBodyParts: ["CORE", "QUADS"],
    skillLevel: "INTERMEDIATE",
    metrics: {
      canMeasureLoad: false,
      canMeasureReps: true,
      canMeasureDuration: false,
      canMeasureDistance: true,
      canMeasureCalories: false,
    },
  }),
];

export const CORE_GYMNASTIC_SEEDS: readonly ExerciseSeed[] = [...corePattern, ...gymnasticSkill];
