import {
  barbellExercise,
  bodyweightExercise,
  dumbbellExercise,
  type ExerciseSeed,
} from "./helpers";

const olympicCombo: ExerciseSeed[] = [
  barbellExercise({
    name: "Snatch",
    nameAliases: ["Squat Snatch", "Full Snatch"],
    description: "Bar from floor to overhead in one motion with full squat receive.",
    primaryMovement: "COMBO",
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["POSTERIOR_CHAIN", "SHOULDERS", "QUADS"],
    skillLevel: "ADVANCED",
    isBenchmark: true,
  }),
  barbellExercise({
    name: "Power Snatch",
    description: "Snatch caught above parallel, no full squat.",
    primaryMovement: "COMBO",
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["POSTERIOR_CHAIN", "SHOULDERS"],
    skillLevel: "ADVANCED",
  }),
  barbellExercise({
    name: "Hang Snatch",
    description: "Snatch starting from above-knee hang position.",
    primaryMovement: "COMBO",
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["POSTERIOR_CHAIN", "SHOULDERS"],
    skillLevel: "ADVANCED",
  }),
  barbellExercise({
    name: "Muscle Snatch",
    description: "Snatch without re-bend of knees, finish overhead with locked legs.",
    primaryMovement: "COMBO",
    primaryBodyParts: ["SHOULDERS", "BACK"],
    secondaryBodyParts: ["POSTERIOR_CHAIN"],
    skillLevel: "INTERMEDIATE",
  }),
  barbellExercise({
    name: "Clean",
    nameAliases: ["Squat Clean", "Full Clean"],
    description: "Bar from floor to front rack with full squat receive.",
    primaryMovement: "COMBO",
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["POSTERIOR_CHAIN", "QUADS", "SHOULDERS"],
    skillLevel: "ADVANCED",
    isBenchmark: true,
  }),
  barbellExercise({
    name: "Power Clean",
    description: "Clean caught above parallel, no full squat.",
    primaryMovement: "COMBO",
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["POSTERIOR_CHAIN", "SHOULDERS"],
    skillLevel: "INTERMEDIATE",
  }),
  barbellExercise({
    name: "Hang Clean",
    description: "Clean starting from above-knee hang position.",
    primaryMovement: "COMBO",
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["POSTERIOR_CHAIN", "SHOULDERS"],
    skillLevel: "INTERMEDIATE",
  }),
  barbellExercise({
    name: "Clean and Jerk",
    nameAliases: ["C&J"],
    description: "Clean from floor followed by jerk to overhead lockout.",
    primaryMovement: "COMBO",
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["POSTERIOR_CHAIN", "SHOULDERS", "QUADS"],
    skillLevel: "ADVANCED",
    isBenchmark: true,
  }),
  barbellExercise({
    name: "Thruster",
    description: "Front squat to push press in one continuous motion.",
    primaryMovement: "COMBO",
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["QUADS", "SHOULDERS", "CORE"],
    skillLevel: "INTERMEDIATE",
  }),
  {
    name: "Wall Ball",
    nameAliases: ["Wall Ball Shot", "WB"],
    description: "Front squat with med ball, throw to target on wall at top.",
    primaryMovement: "COMBO",
    modality: "MIXED",
    equipment: ["medball", "wall"],
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["QUADS", "SHOULDERS", "CORE"],
    skillLevel: "BEGINNER",
    defaultMetrics: {
      canMeasureLoad: true,
      canMeasureReps: true,
      canMeasureDuration: false,
      canMeasureDistance: false,
      canMeasureCalories: false,
    },
    isBenchmark: false,
  },
];

const lungePattern: ExerciseSeed[] = [
  bodyweightExercise({
    name: "Walking Lunge",
    description: "Step forward into lunge, alternate legs while moving forward.",
    primaryMovement: "LUNGE",
    primaryBodyParts: ["QUADS", "GLUTES"],
    secondaryBodyParts: ["HAMSTRINGS", "CORE"],
    skillLevel: "BEGINNER",
  }),
  dumbbellExercise({
    name: "DB Walking Lunge",
    nameAliases: ["Loaded Lunge"],
    description: "Walking lunge holding dumbbells at sides or front rack.",
    primaryMovement: "LUNGE",
    primaryBodyParts: ["QUADS", "GLUTES"],
    secondaryBodyParts: ["HAMSTRINGS", "CORE"],
    skillLevel: "INTERMEDIATE",
  }),
  bodyweightExercise({
    name: "Reverse Lunge",
    description: "Step backward into lunge, drive front leg to return.",
    primaryMovement: "LUNGE",
    primaryBodyParts: ["QUADS", "GLUTES"],
    secondaryBodyParts: ["HAMSTRINGS", "CORE"],
    skillLevel: "BEGINNER",
  }),
  bodyweightExercise({
    name: "Jumping Lunge",
    nameAliases: ["Split Jump"],
    description: "Lunge with explosive jump and switch legs mid-air.",
    primaryMovement: "LUNGE",
    primaryBodyParts: ["QUADS", "GLUTES"],
    secondaryBodyParts: ["CALVES", "CORE"],
    skillLevel: "INTERMEDIATE",
  }),
];

const carryPattern: ExerciseSeed[] = [
  dumbbellExercise({
    name: "Farmer Carry",
    nameAliases: ["Farmer's Walk"],
    description: "Walk with dumbbells at sides, stay tall with engaged core.",
    primaryMovement: "CARRY",
    primaryBodyParts: ["FULL_BODY"],
    secondaryBodyParts: ["CORE", "BACK"],
    skillLevel: "BEGINNER",
  }),
  {
    name: "Suitcase Carry",
    nameAliases: ["Single-side Carry"],
    description: "Walk holding kettlebell on one side, resist lateral flexion.",
    primaryMovement: "CARRY",
    modality: "KETTLEBELL",
    equipment: ["kettlebell"],
    primaryBodyParts: ["CORE", "FULL_BODY"],
    secondaryBodyParts: ["BACK"],
    skillLevel: "BEGINNER",
    defaultMetrics: {
      canMeasureLoad: true,
      canMeasureReps: false,
      canMeasureDuration: true,
      canMeasureDistance: true,
      canMeasureCalories: false,
    },
    isBenchmark: false,
  },
  {
    name: "Front Rack Carry",
    nameAliases: ["FR Carry"],
    description: "Walk with bar in front rack, vertical torso and braced core.",
    primaryMovement: "CARRY",
    modality: "BARBELL",
    equipment: ["barbell"],
    primaryBodyParts: ["CORE", "SHOULDERS"],
    secondaryBodyParts: ["FULL_BODY"],
    skillLevel: "INTERMEDIATE",
    defaultMetrics: {
      canMeasureLoad: true,
      canMeasureReps: false,
      canMeasureDuration: true,
      canMeasureDistance: true,
      canMeasureCalories: false,
    },
    isBenchmark: false,
  },
  {
    name: "Overhead Carry",
    nameAliases: ["OH Carry"],
    description: "Walk with dumbbells locked overhead, shoulders active.",
    primaryMovement: "CARRY",
    modality: "DUMBBELL",
    equipment: ["dumbbell"],
    primaryBodyParts: ["SHOULDERS", "CORE"],
    secondaryBodyParts: ["FULL_BODY"],
    skillLevel: "INTERMEDIATE",
    defaultMetrics: {
      canMeasureLoad: true,
      canMeasureReps: false,
      canMeasureDuration: true,
      canMeasureDistance: true,
      canMeasureCalories: false,
    },
    isBenchmark: false,
  },
];

export const OLYMPIC_COMBO_SEEDS: readonly ExerciseSeed[] = [
  ...olympicCombo,
  ...lungePattern,
  ...carryPattern,
];
