import {
  barbellExercise,
  bodyweightExercise,
  dumbbellExercise,
  type ExerciseSeed,
  kettlebellExercise,
} from "./helpers";

const pullVertical: ExerciseSeed[] = [
  bodyweightExercise({
    name: "Strict Pull-up",
    nameAliases: ["Dead-hang Pull-up", "Pronated Pull-up"],
    description: "From dead hang, pull chin over bar with no kip.",
    primaryMovement: "PULL_VERTICAL",
    equipment: ["pull-up bar"],
    primaryBodyParts: ["BACK", "ARMS_BICEPS"],
    secondaryBodyParts: ["SHOULDERS", "CORE"],
    skillLevel: "INTERMEDIATE",
    isBenchmark: true,
  }),
  bodyweightExercise({
    name: "Kipping Pull-up",
    description: "Use hip drive and arch-hollow rhythm to pull chin over bar.",
    primaryMovement: "PULL_VERTICAL",
    equipment: ["pull-up bar"],
    primaryBodyParts: ["BACK", "ARMS_BICEPS"],
    secondaryBodyParts: ["SHOULDERS", "CORE"],
    skillLevel: "INTERMEDIATE",
  }),
  bodyweightExercise({
    name: "Butterfly Pull-up",
    description: "Continuous-cycle kipping pull-up for high-volume sets.",
    primaryMovement: "PULL_VERTICAL",
    equipment: ["pull-up bar"],
    primaryBodyParts: ["BACK", "ARMS_BICEPS"],
    secondaryBodyParts: ["SHOULDERS", "CORE"],
    skillLevel: "ADVANCED",
  }),
  bodyweightExercise({
    name: "Chest-to-bar Pull-up",
    nameAliases: ["C2B"],
    description: "Pull-up where chest contacts bar at top, kipping or strict.",
    primaryMovement: "PULL_VERTICAL",
    equipment: ["pull-up bar"],
    primaryBodyParts: ["BACK", "ARMS_BICEPS"],
    secondaryBodyParts: ["SHOULDERS", "CHEST"],
    skillLevel: "ADVANCED",
  }),
  bodyweightExercise({
    name: "Bar Muscle-up",
    nameAliases: ["BMU"],
    description: "Kipping pull-up to transition over bar into support, finish with dip.",
    primaryMovement: "COMBO",
    equipment: ["pull-up bar"],
    primaryBodyParts: ["BACK", "CHEST", "ARMS_TRICEPS"],
    secondaryBodyParts: ["CORE", "SHOULDERS"],
    skillLevel: "ADVANCED",
  }),
  bodyweightExercise({
    name: "Ring Muscle-up",
    nameAliases: ["RMU"],
    description: "Pull-to-transition on rings, finish at support with locked arms.",
    primaryMovement: "COMBO",
    equipment: ["rings"],
    primaryBodyParts: ["BACK", "CHEST", "ARMS_TRICEPS"],
    secondaryBodyParts: ["CORE", "SHOULDERS"],
    skillLevel: "ELITE",
  }),
  bodyweightExercise({
    name: "Chin-up",
    nameAliases: ["Supinated Pull-up"],
    description: "Pull-up with palms facing body, bicep emphasis.",
    primaryMovement: "PULL_VERTICAL",
    equipment: ["pull-up bar"],
    primaryBodyParts: ["ARMS_BICEPS", "BACK"],
    secondaryBodyParts: ["SHOULDERS"],
    skillLevel: "INTERMEDIATE",
  }),
  {
    name: "Banded Pull-up",
    nameAliases: ["Assisted Pull-up"],
    description: "Pull-up with band assistance for added support.",
    primaryMovement: "PULL_VERTICAL",
    modality: "BANDED",
    equipment: ["pull-up bar", "band"],
    primaryBodyParts: ["BACK", "ARMS_BICEPS"],
    secondaryBodyParts: ["SHOULDERS"],
    skillLevel: "BEGINNER",
    defaultMetrics: {
      canMeasureLoad: false,
      canMeasureReps: true,
      canMeasureDuration: false,
      canMeasureDistance: false,
      canMeasureCalories: false,
    },
    isBenchmark: false,
  },
];

const pullHorizontal: ExerciseSeed[] = [
  barbellExercise({
    name: "Pendlay Row",
    description: "Row from floor with strict form, bar returns to ground each rep.",
    primaryMovement: "PULL_HORIZONTAL",
    primaryBodyParts: ["BACK", "ARMS_BICEPS"],
    secondaryBodyParts: ["SHOULDERS", "CORE"],
    skillLevel: "INTERMEDIATE",
  }),
  barbellExercise({
    name: "Bent-over Row",
    nameAliases: ["BB Row"],
    description: "Hinged torso, pull bar to lower chest with retracted scapulae.",
    primaryMovement: "PULL_HORIZONTAL",
    primaryBodyParts: ["BACK", "ARMS_BICEPS"],
    secondaryBodyParts: ["SHOULDERS", "POSTERIOR_CHAIN"],
    skillLevel: "INTERMEDIATE",
  }),
  dumbbellExercise({
    name: "DB Row",
    nameAliases: ["Single-arm DB Row"],
    description: "One arm braced on bench, row dumbbell to hip with retracted scapula.",
    primaryMovement: "PULL_HORIZONTAL",
    equipment: ["dumbbell", "bench"],
    primaryBodyParts: ["BACK", "ARMS_BICEPS"],
    secondaryBodyParts: ["SHOULDERS", "CORE"],
    skillLevel: "BEGINNER",
  }),
  kettlebellExercise({
    name: "KB Row",
    description: "Hinge at hip, row kettlebell with retracted scapula.",
    primaryMovement: "PULL_HORIZONTAL",
    primaryBodyParts: ["BACK", "ARMS_BICEPS"],
    secondaryBodyParts: ["SHOULDERS", "POSTERIOR_CHAIN"],
    skillLevel: "BEGINNER",
  }),
  bodyweightExercise({
    name: "Inverted Row",
    description: "Body horizontal under bar, pull chest to bar with straight body.",
    primaryMovement: "PULL_HORIZONTAL",
    equipment: ["pull-up bar"],
    primaryBodyParts: ["BACK", "ARMS_BICEPS"],
    secondaryBodyParts: ["SHOULDERS", "CORE"],
    skillLevel: "BEGINNER",
  }),
  bodyweightExercise({
    name: "Ring Row",
    description: "Body horizontal under rings, pull chest to rings with control.",
    primaryMovement: "PULL_HORIZONTAL",
    equipment: ["rings"],
    primaryBodyParts: ["BACK", "ARMS_BICEPS"],
    secondaryBodyParts: ["SHOULDERS", "CORE"],
    skillLevel: "BEGINNER",
  }),
];

export const PULL_SEEDS: readonly ExerciseSeed[] = [...pullVertical, ...pullHorizontal];
