import {
  barbellExercise,
  bodyweightExercise,
  dumbbellExercise,
  type ExerciseSeed,
  kettlebellExercise,
} from "./helpers";

const pushVertical: ExerciseSeed[] = [
  barbellExercise({
    name: "Strict Press",
    nameAliases: ["Shoulder Press", "OHP", "Military Press"],
    description: "Bar from front rack to overhead with no leg drive.",
    primaryMovement: "PUSH_VERTICAL",
    primaryBodyParts: ["SHOULDERS", "ARMS_TRICEPS"],
    secondaryBodyParts: ["CORE", "CHEST"],
    skillLevel: "BEGINNER",
    isBenchmark: true,
  }),
  barbellExercise({
    name: "Push Press",
    description: "Dip and drive with legs, bar finishes locked overhead.",
    primaryMovement: "PUSH_VERTICAL",
    primaryBodyParts: ["SHOULDERS", "ARMS_TRICEPS"],
    secondaryBodyParts: ["QUADS", "CORE"],
    skillLevel: "INTERMEDIATE",
  }),
  barbellExercise({
    name: "Push Jerk",
    description: "Dip-drive followed by re-bend of knees to receive bar overhead.",
    primaryMovement: "PUSH_VERTICAL",
    primaryBodyParts: ["SHOULDERS", "ARMS_TRICEPS"],
    secondaryBodyParts: ["QUADS", "CORE"],
    skillLevel: "ADVANCED",
  }),
  barbellExercise({
    name: "Split Jerk",
    description: "Dip-drive with split-stance receive, bar locked overhead.",
    primaryMovement: "PUSH_VERTICAL",
    primaryBodyParts: ["SHOULDERS", "ARMS_TRICEPS"],
    secondaryBodyParts: ["QUADS", "GLUTES", "CORE"],
    skillLevel: "ADVANCED",
  }),
  dumbbellExercise({
    name: "DB Shoulder Press",
    nameAliases: ["Dumbbell Press", "DB Press"],
    description: "Dumbbells from shoulders to overhead, palms facing forward.",
    primaryMovement: "PUSH_VERTICAL",
    primaryBodyParts: ["SHOULDERS", "ARMS_TRICEPS"],
    secondaryBodyParts: ["CORE"],
    skillLevel: "BEGINNER",
  }),
  kettlebellExercise({
    name: "KB Press",
    nameAliases: ["Kettlebell Strict Press"],
    description: "Kettlebell from rack to overhead with no leg drive.",
    primaryMovement: "PUSH_VERTICAL",
    primaryBodyParts: ["SHOULDERS", "ARMS_TRICEPS"],
    secondaryBodyParts: ["CORE"],
    skillLevel: "INTERMEDIATE",
  }),
  bodyweightExercise({
    name: "Handstand Push-up",
    nameAliases: ["HSPU"],
    description: "Inverted against wall, lower head to ground, press to lockout.",
    primaryMovement: "PUSH_VERTICAL",
    equipment: ["wall"],
    primaryBodyParts: ["SHOULDERS", "ARMS_TRICEPS"],
    secondaryBodyParts: ["CORE"],
    skillLevel: "ADVANCED",
  }),
  bodyweightExercise({
    name: "Wall-Walk",
    description: "Walk hands toward wall while feet climb, reach inverted position.",
    primaryMovement: "GYMNASTIC_INVERTED",
    equipment: ["wall"],
    primaryBodyParts: ["SHOULDERS", "CORE"],
    secondaryBodyParts: ["ARMS_TRICEPS"],
    skillLevel: "INTERMEDIATE",
  }),
  bodyweightExercise({
    name: "Pike Push-up",
    description: "Hips piked high, lower head toward ground, press to lockout.",
    primaryMovement: "PUSH_VERTICAL",
    primaryBodyParts: ["SHOULDERS", "ARMS_TRICEPS"],
    secondaryBodyParts: ["CORE"],
    skillLevel: "INTERMEDIATE",
  }),
  barbellExercise({
    name: "Z Press",
    description: "Seated on floor with legs extended, press bar overhead from rack.",
    primaryMovement: "PUSH_VERTICAL",
    primaryBodyParts: ["SHOULDERS", "CORE"],
    secondaryBodyParts: ["ARMS_TRICEPS"],
    skillLevel: "INTERMEDIATE",
  }),
];

const pushHorizontal: ExerciseSeed[] = [
  barbellExercise({
    name: "Bench Press",
    nameAliases: ["Flat Bench"],
    description: "Lying on bench, lower bar to chest, press to full lockout.",
    primaryMovement: "PUSH_HORIZONTAL",
    equipment: ["barbell", "bench"],
    primaryBodyParts: ["CHEST", "ARMS_TRICEPS"],
    secondaryBodyParts: ["SHOULDERS"],
    skillLevel: "BEGINNER",
    isBenchmark: true,
  }),
  barbellExercise({
    name: "Close-grip Bench Press",
    nameAliases: ["CGBP"],
    description: "Bench press with hands at shoulder width, elbows tucked.",
    primaryMovement: "PUSH_HORIZONTAL",
    equipment: ["barbell", "bench"],
    primaryBodyParts: ["ARMS_TRICEPS", "CHEST"],
    secondaryBodyParts: ["SHOULDERS"],
    skillLevel: "INTERMEDIATE",
  }),
  barbellExercise({
    name: "Incline Bench Press",
    description: "Bench press on inclined bench, targets upper chest.",
    primaryMovement: "PUSH_HORIZONTAL",
    equipment: ["barbell", "bench"],
    primaryBodyParts: ["CHEST", "SHOULDERS"],
    secondaryBodyParts: ["ARMS_TRICEPS"],
    skillLevel: "INTERMEDIATE",
  }),
  barbellExercise({
    name: "Floor Press",
    description: "Bench press lying on floor, elbows touch ground at bottom.",
    primaryMovement: "PUSH_HORIZONTAL",
    primaryBodyParts: ["CHEST", "ARMS_TRICEPS"],
    secondaryBodyParts: ["SHOULDERS"],
    skillLevel: "INTERMEDIATE",
  }),
  dumbbellExercise({
    name: "DB Bench Press",
    description: "Lying on bench, dumbbells lowered to sides of chest, pressed to lockout.",
    primaryMovement: "PUSH_HORIZONTAL",
    primaryBodyParts: ["CHEST", "ARMS_TRICEPS"],
    secondaryBodyParts: ["SHOULDERS"],
    skillLevel: "BEGINNER",
  }),
  bodyweightExercise({
    name: "Push-up",
    nameAliases: ["Standard Push-up"],
    description: "Plank position, lower chest to floor, press to lockout.",
    primaryMovement: "PUSH_HORIZONTAL",
    primaryBodyParts: ["CHEST", "ARMS_TRICEPS"],
    secondaryBodyParts: ["SHOULDERS", "CORE"],
    skillLevel: "BEGINNER",
  }),
  bodyweightExercise({
    name: "Ring Push-up",
    description: "Push-up on rings, requires constant stabilization.",
    primaryMovement: "PUSH_HORIZONTAL",
    equipment: ["rings"],
    primaryBodyParts: ["CHEST", "ARMS_TRICEPS"],
    secondaryBodyParts: ["SHOULDERS", "CORE"],
    skillLevel: "INTERMEDIATE",
  }),
  bodyweightExercise({
    name: "Diamond Push-up",
    nameAliases: ["Tricep Push-up"],
    description: "Push-up with hands together forming diamond, elbows tucked.",
    primaryMovement: "PUSH_HORIZONTAL",
    primaryBodyParts: ["ARMS_TRICEPS", "CHEST"],
    secondaryBodyParts: ["SHOULDERS"],
    skillLevel: "INTERMEDIATE",
  }),
];

export const PUSH_SEEDS: readonly ExerciseSeed[] = [...pushVertical, ...pushHorizontal];
