import {
  barbellExercise,
  bodyweightExercise,
  dumbbellExercise,
  type ExerciseSeed,
  kettlebellExercise,
} from "./helpers";

const squatPattern: ExerciseSeed[] = [
  barbellExercise({
    name: "Back Squat",
    nameAliases: ["High-Bar Back Squat", "BS"],
    description: "Bar across upper traps, hips below parallel, drive through full foot.",
    primaryMovement: "SQUAT",
    primaryBodyParts: ["QUADS", "GLUTES"],
    secondaryBodyParts: ["CORE", "POSTERIOR_CHAIN"],
    skillLevel: "BEGINNER",
    isBenchmark: true,
  }),
  barbellExercise({
    name: "Front Squat",
    nameAliases: ["FS"],
    description: "Bar in front rack, elbows high, vertical torso, hips below parallel.",
    primaryMovement: "SQUAT",
    primaryBodyParts: ["QUADS", "CORE"],
    secondaryBodyParts: ["GLUTES", "SHOULDERS"],
    skillLevel: "INTERMEDIATE",
    isBenchmark: true,
  }),
  barbellExercise({
    name: "Overhead Squat",
    nameAliases: ["OHS"],
    description: "Bar locked overhead, full depth squat with active shoulders.",
    primaryMovement: "SQUAT",
    primaryBodyParts: ["QUADS", "SHOULDERS"],
    secondaryBodyParts: ["CORE", "GLUTES"],
    skillLevel: "ADVANCED",
  }),
  kettlebellExercise({
    name: "Goblet Squat",
    description: "Hold kettlebell at chest, full depth squat with vertical torso.",
    primaryMovement: "SQUAT",
    primaryBodyParts: ["QUADS", "GLUTES"],
    secondaryBodyParts: ["CORE"],
    skillLevel: "BEGINNER",
  }),
  barbellExercise({
    name: "Box Squat",
    description: "Squat to a box, pause briefly, drive up through full foot.",
    primaryMovement: "SQUAT",
    primaryBodyParts: ["QUADS", "GLUTES"],
    secondaryBodyParts: ["POSTERIOR_CHAIN"],
    skillLevel: "INTERMEDIATE",
  }),
  bodyweightExercise({
    name: "Air Squat",
    nameAliases: ["Bodyweight Squat"],
    description: "Hands free or out front, hips below knees, knees track toes.",
    primaryMovement: "SQUAT",
    primaryBodyParts: ["QUADS", "GLUTES"],
    secondaryBodyParts: ["CORE"],
    skillLevel: "BEGINNER",
  }),
  bodyweightExercise({
    name: "Pistol Squat",
    nameAliases: ["Single-leg Squat"],
    description: "Single-leg squat to full depth, opposite leg extended forward.",
    primaryMovement: "SQUAT",
    primaryBodyParts: ["QUADS", "GLUTES"],
    secondaryBodyParts: ["CORE", "HAMSTRINGS"],
    skillLevel: "ADVANCED",
  }),
  dumbbellExercise({
    name: "Bulgarian Split Squat",
    nameAliases: ["Rear-foot Elevated Split Squat", "RFE Split Squat"],
    description: "Rear foot elevated on bench, descend into split squat with front leg.",
    primaryMovement: "SQUAT",
    primaryBodyParts: ["QUADS", "GLUTES"],
    secondaryBodyParts: ["HAMSTRINGS", "CORE"],
    skillLevel: "INTERMEDIATE",
  }),
  bodyweightExercise({
    name: "Wall Sit",
    description: "Back flat against wall, knees bent at 90 degrees, hold isometrically.",
    primaryMovement: "SQUAT",
    primaryBodyParts: ["QUADS"],
    secondaryBodyParts: ["GLUTES", "CORE"],
    skillLevel: "BEGINNER",
    metrics: {
      canMeasureLoad: false,
      canMeasureReps: false,
      canMeasureDuration: true,
      canMeasureDistance: false,
      canMeasureCalories: false,
    },
  }),
  barbellExercise({
    name: "Sumo Squat",
    nameAliases: ["Wide-stance Squat"],
    description: "Wide stance, toes turned out, descend with vertical torso.",
    primaryMovement: "SQUAT",
    primaryBodyParts: ["QUADS", "GLUTES"],
    secondaryBodyParts: ["HIPS"],
    skillLevel: "BEGINNER",
  }),
];

const hingePattern: ExerciseSeed[] = [
  barbellExercise({
    name: "Deadlift",
    nameAliases: ["Conventional Deadlift", "DL"],
    description: "Hip-width stance, lift bar from floor with neutral spine, full hip extension.",
    primaryMovement: "HINGE",
    primaryBodyParts: ["POSTERIOR_CHAIN", "GLUTES"],
    secondaryBodyParts: ["HAMSTRINGS", "BACK", "CORE"],
    skillLevel: "BEGINNER",
    isBenchmark: true,
  }),
  barbellExercise({
    name: "Sumo Deadlift",
    description: "Wide stance, hands inside knees, vertical torso through pull.",
    primaryMovement: "HINGE",
    primaryBodyParts: ["POSTERIOR_CHAIN", "GLUTES"],
    secondaryBodyParts: ["QUADS", "BACK"],
    skillLevel: "INTERMEDIATE",
  }),
  barbellExercise({
    name: "Romanian Deadlift",
    nameAliases: ["RDL"],
    description: "Slight knee bend, hinge at hips with neutral spine, bar tracks legs.",
    primaryMovement: "HINGE",
    primaryBodyParts: ["HAMSTRINGS", "GLUTES"],
    secondaryBodyParts: ["BACK", "POSTERIOR_CHAIN"],
    skillLevel: "INTERMEDIATE",
  }),
  dumbbellExercise({
    name: "Single-leg Deadlift",
    nameAliases: ["SLDL"],
    description: "Hinge on one leg, opposite leg extends behind, slight knee bend.",
    primaryMovement: "HINGE",
    primaryBodyParts: ["HAMSTRINGS", "GLUTES"],
    secondaryBodyParts: ["CORE", "BACK"],
    skillLevel: "INTERMEDIATE",
  }),
  kettlebellExercise({
    name: "Kettlebell Swing",
    nameAliases: ["KB Swing"],
    description: "Hip-hinge swing, bell driven by hip extension to chest height.",
    primaryMovement: "HINGE",
    primaryBodyParts: ["POSTERIOR_CHAIN", "GLUTES"],
    secondaryBodyParts: ["HAMSTRINGS", "CORE"],
    skillLevel: "BEGINNER",
  }),
  kettlebellExercise({
    name: "American KB Swing",
    description: "Kettlebell swing finishing fully overhead with arms locked out.",
    primaryMovement: "HINGE",
    primaryBodyParts: ["POSTERIOR_CHAIN", "SHOULDERS"],
    secondaryBodyParts: ["GLUTES", "CORE"],
    skillLevel: "INTERMEDIATE",
  }),
  kettlebellExercise({
    name: "Russian KB Swing",
    description: "Kettlebell swing to chest level, hips drive movement.",
    primaryMovement: "HINGE",
    primaryBodyParts: ["POSTERIOR_CHAIN", "GLUTES"],
    secondaryBodyParts: ["HAMSTRINGS", "CORE"],
    skillLevel: "BEGINNER",
  }),
  barbellExercise({
    name: "Good Morning",
    description: "Bar on upper back, hinge forward keeping neutral spine.",
    primaryMovement: "HINGE",
    primaryBodyParts: ["HAMSTRINGS", "POSTERIOR_CHAIN"],
    secondaryBodyParts: ["GLUTES", "BACK"],
    skillLevel: "INTERMEDIATE",
  }),
  barbellExercise({
    name: "Hip Thrust",
    nameAliases: ["Barbell Hip Thrust"],
    description: "Upper back on bench, drive bar up with full hip extension.",
    primaryMovement: "HINGE",
    primaryBodyParts: ["GLUTES"],
    secondaryBodyParts: ["HAMSTRINGS", "CORE"],
    skillLevel: "BEGINNER",
  }),
  bodyweightExercise({
    name: "Glute Bridge",
    description: "Lying on back, drive hips up squeezing glutes at top.",
    primaryMovement: "HINGE",
    primaryBodyParts: ["GLUTES"],
    secondaryBodyParts: ["HAMSTRINGS", "CORE"],
    skillLevel: "BEGINNER",
  }),
];

export const SQUAT_HINGE_SEEDS: readonly ExerciseSeed[] = [...squatPattern, ...hingePattern];
