export { createBlogAPI } from "./blog";
export { createContactsAPI } from "./contacts";
export { createDashboardAPI } from "./dashboard";
export { createExercisesAPI } from "./exercises";
export { createPagesAPI } from "./pages";
export { createProductsAPI } from "./products";
export { createReviewsAPI } from "./reviews";
export { createUploadAPI } from "./upload";
export { createUsersAPI } from "./users";
