import type { ExerciseCatalogEntry } from "../canonical-schema";

import { atomic, compound, placeholder } from "./catalog-exercises-helpers";

const BODYWEIGHT_EXERCISES: ExerciseCatalogEntry[] = [
  atomic("demo-pull-up", "Demo Pull-up", "BODYWEIGHT", "PULL", "pull-up", {
    demo: "https://example.com/demo/pull-up",
  }),
  atomic("demo-strict-pull-up", "Demo Strict Pull-up", "BODYWEIGHT", "PULL", "pull-up"),
  atomic("demo-c2b-pull-up", "Demo Chest-to-bar Pull-up", "BODYWEIGHT", "PULL", "pull-up"),
  atomic("demo-bar-muscle-up", "Demo Bar Muscle-up", "BODYWEIGHT", "PULL", "muscle-up"),
  atomic("demo-toes-to-bar", "Demo Toes-to-bar", "BODYWEIGHT", "CORE", "core"),
  atomic("demo-knees-to-elbows", "Demo Knees-to-elbows", "BODYWEIGHT", "CORE", "core"),
  atomic("demo-strict-hspu", "Demo Strict HSPU", "BODYWEIGHT", "PRESS", "handstand"),
  atomic("demo-kipping-hspu", "Demo Kipping HSPU", "BODYWEIGHT", "PRESS", "handstand"),
  atomic("demo-hs-walk", "Demo Handstand Walk", "BODYWEIGHT", "LOCOMOTION", "handstand"),
  atomic("demo-pike-push-up", "Demo Pike Push-up", "BODYWEIGHT", "PRESS", "push-up"),
  atomic("demo-push-up", "Demo Push-up", "BODYWEIGHT", "PRESS", "push-up"),
  atomic("demo-clap-push-up", "Demo Clap Push-up", "BODYWEIGHT", "PRESS", "push-up"),
  atomic("demo-air-squat", "Demo Air Squat", "BODYWEIGHT", "SQUAT", "squat"),
  atomic("demo-pistol-squat", "Demo Pistol Squat", "BODYWEIGHT", "SQUAT", "squat"),
  atomic("demo-jump-squat", "Demo Jump Squat", "BODYWEIGHT", "SQUAT", "squat"),
  atomic("demo-burpee", "Demo Burpee", "BODYWEIGHT", "LOCOMOTION", "burpee"),
  atomic(
    "demo-burpee-box-jump-over",
    "Demo Burpee Box Jump Over",
    "BODYWEIGHT",
    "LOCOMOTION",
    "burpee",
  ),
  atomic("demo-box-jump", "Demo Box Jump", "BODYWEIGHT", "LOCOMOTION", "box-jump"),
  atomic("demo-box-step-up", "Demo Box Step Up", "BODYWEIGHT", "LUNGE", "lunge"),
  atomic("demo-walking-lunge", "Demo Walking Lunge", "BODYWEIGHT", "LUNGE", "lunge"),
  atomic("demo-sit-up", "Demo Sit-up", "BODYWEIGHT", "CORE", "core"),
  atomic("demo-v-up", "Demo V-up", "BODYWEIGHT", "CORE", "core"),
  atomic("demo-hollow-hold", "Demo Hollow Hold", "BODYWEIGHT", "STATIC_HOLD", "core"),
  atomic("demo-plank-hold", "Demo Plank Hold", "BODYWEIGHT", "STATIC_HOLD", "core"),
  atomic("demo-side-plank-hold", "Demo Side Plank Hold", "BODYWEIGHT", "STATIC_HOLD", "core"),
  atomic("demo-l-sit-hold", "Demo L-sit Hold", "PARALLEL_BARS", "STATIC_HOLD", "core"),
  atomic("demo-ring-row", "Demo Ring Row", "RINGS", "PULL", "row"),
  atomic("demo-strict-ring-pull-up", "Demo Strict Ring Pull-up", "RINGS", "PULL", "pull-up"),
  atomic("demo-ring-muscle-up", "Demo Ring Muscle-up", "RINGS", "PULL", "muscle-up"),
  atomic("demo-ring-dip", "Demo Ring Dip", "RINGS", "PRESS", "dip"),
  atomic("demo-bar-dip", "Demo Bar Dip", "PARALLEL_BARS", "PRESS", "dip"),
  atomic("demo-rope-climb", "Demo Rope Climb", "BODYWEIGHT", "LOCOMOTION", "rope"),
  atomic("demo-bear-crawl", "Demo Bear Crawl", "BODYWEIGHT", "LOCOMOTION", "crawl"),
  atomic("demo-crab-walk", "Demo Crab Walk", "BODYWEIGHT", "LOCOMOTION", "crawl"),
  atomic("demo-broad-jump", "Demo Broad Jump", "BODYWEIGHT", "LOCOMOTION", "jump"),
  atomic("demo-double-under", "Demo Double Under", "JUMP_ROPE", "CARDIO_FLOW", "jump-rope"),
  atomic("demo-single-under", "Demo Single Under", "JUMP_ROPE", "CARDIO_FLOW", "jump-rope"),
  atomic("demo-crossover-skip", "Demo Crossover Skip", "JUMP_ROPE", "CARDIO_FLOW", "jump-rope"),
  atomic("demo-run", "Demo Run", "BODYWEIGHT", "LOCOMOTION", "run"),
  atomic("demo-shuttle-run", "Demo Shuttle Run", "BODYWEIGHT", "LOCOMOTION", "run"),
  atomic("demo-sprint", "Demo Sprint", "BODYWEIGHT", "LOCOMOTION", "run"),
  atomic("demo-kipping-pull-up", "Demo Kipping Pull-up", "BODYWEIGHT", "PULL", "pull-up"),
  atomic("demo-butterfly-pull-up", "Demo Butterfly Pull-up", "BODYWEIGHT", "PULL", "pull-up"),
  atomic("demo-strict-toes-to-bar", "Demo Strict Toes-to-bar", "BODYWEIGHT", "CORE", "core"),
  atomic("demo-hollow-rock", "Demo Hollow Rock", "BODYWEIGHT", "CORE", "core"),
  atomic("demo-arch-hold", "Demo Arch Hold", "BODYWEIGHT", "STATIC_HOLD", "core"),
  atomic("demo-handstand-hold", "Demo Handstand Hold", "BODYWEIGHT", "STATIC_HOLD", "handstand"),
];

const STATIC_AND_ROTATION_EXERCISES: ExerciseCatalogEntry[] = [
  atomic("demo-russian-twist", "Demo Russian Twist", "BODYWEIGHT", "ROTATIONAL", "rotation"),
  atomic("demo-bb-rotation", "Demo Barbell Rotation", "BARBELL", "ROTATIONAL", "rotation"),
  atomic(
    "demo-mb-rotation-throw",
    "Demo Medball Rotation Throw",
    "MIXED",
    "ROTATIONAL",
    "rotation",
  ),
  atomic("demo-pallof-press", "Demo Pallof Press", "BAND", "ROTATIONAL", "rotation"),
  atomic("demo-windshield-wiper", "Demo Windshield Wiper", "BODYWEIGHT", "ROTATIONAL", "rotation"),
  atomic("demo-back-extension", "Demo Back Extension", "BODYWEIGHT", "EXTENSION", "back"),
  atomic("demo-ghd-back-extension", "Demo GHD Back Extension", "BODYWEIGHT", "EXTENSION", "back"),
  atomic("demo-ghd-sit-up", "Demo GHD Sit-up", "BODYWEIGHT", "CORE", "core"),
];

const COMPOUND_EXERCISES: ExerciseCatalogEntry[] = [
  compound(
    "demo-thruster-pull-up",
    "Demo Thruster + Pull-up Complex",
    "MIXED",
    "COMBINED_OLYMPIC",
    "thruster",
    "COMPOUND_PLUS",
  ),
  compound(
    "demo-clean-jerk-complex",
    "Demo Clean + Jerk Complex",
    "BARBELL",
    "COMBINED_OLYMPIC",
    "clean",
    "COMPOUND_PLUS",
  ),
  compound(
    "demo-snatch-balance-complex",
    "Demo Snatch + Balance Complex",
    "BARBELL",
    "COMBINED_OLYMPIC",
    "snatch",
    "COMPOUND_PLUS",
  ),
  compound(
    "demo-db-press-push-press",
    "Demo DB Press + Push Press",
    "DUMBBELL",
    "PRESS",
    "press",
    "COMPOUND_PLUS",
  ),
  compound(
    "demo-strict-press-push-press",
    "Demo Strict Press + Push Press",
    "BARBELL",
    "PRESS",
    "press",
    "COMPOUND_PLUS",
  ),
  compound(
    "demo-row-burpee",
    "Demo Row + Burpee Composite",
    "MIXED",
    "CARDIO_FLOW",
    "row",
    "COMPOSITE_NAMED",
  ),
  compound(
    "demo-dt-complex",
    "Demo DT (Deadlift + Hang Clean + Push Jerk)",
    "BARBELL",
    "COMBINED_OLYMPIC",
    "dt",
    "COMPOSITE_NAMED",
  ),
  compound(
    "demo-grace-complex",
    "Demo Grace (Clean and Jerk × 30)",
    "BARBELL",
    "COMBINED_OLYMPIC",
    "grace",
    "COMPOSITE_NAMED",
  ),
  compound(
    "demo-fran-complex",
    "Demo Fran (Thruster + Pull-up Couplet)",
    "MIXED",
    "COMBINED_OLYMPIC",
    "fran",
    "COMPOSITE_NAMED",
  ),
  compound(
    "demo-pull-up-or-ring-row",
    "Demo Pull-up OR Ring Row",
    "MIXED",
    "PULL",
    "pull-up",
    "ALTERNATIVE_OR",
  ),
  compound(
    "demo-back-squat-or-goblet",
    "Demo Back Squat OR Goblet Squat",
    "MIXED",
    "SQUAT",
    "squat",
    "ALTERNATIVE_OR",
  ),
];

const PLACEHOLDER_EXERCISES: ExerciseCatalogEntry[] = [
  placeholder("demo-placeholder-biceps-triceps", "Demo Placeholder Biceps / Triceps", "accessory"),
  placeholder("demo-placeholder-coach-choice", "Demo Placeholder Coach Choice", null),
  placeholder("demo-placeholder-abs", "Demo Placeholder Abs", "core"),
  placeholder(
    "demo-placeholder-shoulder-accessory",
    "Demo Placeholder Shoulder Accessory",
    "shoulder",
  ),
  placeholder("demo-placeholder-warm-up", "Demo Placeholder Warm Up", null),
];

export const BODYWEIGHT_AND_COMPOUND_EXERCISES: ExerciseCatalogEntry[] = [
  ...BODYWEIGHT_EXERCISES,
  ...STATIC_AND_ROTATION_EXERCISES,
  ...COMPOUND_EXERCISES,
  ...PLACEHOLDER_EXERCISES,
];
