import { exerciseCuid } from "../builder";

export const EX = {
  backSquat: exerciseCuid("Demo Back Squat"),
  frontSquat: exerciseCuid("Demo Front Squat"),
  overheadSquat: exerciseCuid("Demo Overhead Squat"),
  pauseBackSquat: exerciseCuid("Demo Pause Back Squat"),
  conventionalDeadlift: exerciseCuid("Demo Conventional Deadlift"),
  sumoDeadlift: exerciseCuid("Demo Sumo Deadlift"),
  romanianDeadlift: exerciseCuid("Demo Romanian Deadlift"),
  benchPress: exerciseCuid("Demo Bench Press"),
  inclineBenchPress: exerciseCuid("Demo Incline Bench Press"),
  strictPress: exerciseCuid("Demo Strict Press"),
  pushPress: exerciseCuid("Demo Push Press"),
  pushJerk: exerciseCuid("Demo Push Jerk"),
  splitJerk: exerciseCuid("Demo Split Jerk"),
  pendlayRow: exerciseCuid("Demo Pendlay Row"),
  bentOverRow: exerciseCuid("Demo Bent Over Row"),
  bbSnatch: exerciseCuid("Demo Barbell Snatch"),
  powerSnatch: exerciseCuid("Demo Power Snatch"),
  hangSnatch: exerciseCuid("Demo Hang Snatch"),
  bbClean: exerciseCuid("Demo Barbell Clean"),
  powerClean: exerciseCuid("Demo Power Clean"),
  hangClean: exerciseCuid("Demo Hang Clean"),
  thruster: exerciseCuid("Demo Thruster"),
  bbWalkingLunge: exerciseCuid("Demo Barbell Walking Lunge"),
  bbStepUp: exerciseCuid("Demo Barbell Step Up"),
  bbCurl: exerciseCuid("Demo Barbell Curl"),
  dbBenchPress: exerciseCuid("Demo DB Bench Press"),
  dbInclinePress: exerciseCuid("Demo DB Incline Press"),
  dbShoulderPress: exerciseCuid("Demo DB Shoulder Press"),
  dbStrictPress: exerciseCuid("Demo DB Strict Press"),
  dbPushPress: exerciseCuid("Demo DB Push Press"),
  dbRow: exerciseCuid("Demo DB Row"),
  dbRenegadeRow: exerciseCuid("Demo DB Renegade Row"),
  dbSnatch: exerciseCuid("Demo DB Snatch"),
  dbCleanAndJerk: exerciseCuid("Demo DB Clean and Jerk"),
  dbThruster: exerciseCuid("Demo DB Thruster"),
  dbWalkingLunge: exerciseCuid("Demo DB Walking Lunge"),
  dbBulgarianSplitSquat: exerciseCuid("Demo DB Bulgarian Split Squat"),
  dbStepUp: exerciseCuid("Demo DB Step Up"),
  dbGobletSquat: exerciseCuid("Demo DB Goblet Squat"),
  dbCurl: exerciseCuid("Demo DB Curl"),
  dbHammerCurl: exerciseCuid("Demo DB Hammer Curl"),
  dbLateralRaise: exerciseCuid("Demo DB Lateral Raise"),
  dbDeadlift: exerciseCuid("Demo DB Deadlift"),
  kbSwing: exerciseCuid("Demo KB Swing"),
  kbSnatch: exerciseCuid("Demo KB Snatch"),
  kbClean: exerciseCuid("Demo KB Clean"),
  kbPress: exerciseCuid("Demo KB Press"),
  kbRow: exerciseCuid("Demo KB Row"),
  kbGobletSquat: exerciseCuid("Demo KB Goblet Squat"),
  kbFarmersCarry: exerciseCuid("Demo KB Farmers Carry"),
  kbSuitcaseCarry: exerciseCuid("Demo KB Suitcase Carry"),
  kbTurkishGetUp: exerciseCuid("Demo KB Turkish Get Up"),
  pullUp: exerciseCuid("Demo Pull-up"),
  strictPullUp: exerciseCuid("Demo Strict Pull-up"),
  c2bPullUp: exerciseCuid("Demo Chest-to-bar Pull-up"),
  barMuscleUp: exerciseCuid("Demo Bar Muscle-up"),
  toesToBar: exerciseCuid("Demo Toes-to-bar"),
  kneesToElbows: exerciseCuid("Demo Knees-to-elbows"),
  strictHspu: exerciseCuid("Demo Strict HSPU"),
  kippingHspu: exerciseCuid("Demo Kipping HSPU"),
  hsWalk: exerciseCuid("Demo Handstand Walk"),
  pikePushUp: exerciseCuid("Demo Pike Push-up"),
  pushUp: exerciseCuid("Demo Push-up"),
  airSquat: exerciseCuid("Demo Air Squat"),
  pistolSquat: exerciseCuid("Demo Pistol Squat"),
  jumpSquat: exerciseCuid("Demo Jump Squat"),
  burpee: exerciseCuid("Demo Burpee"),
  burpeeBoxJumpOver: exerciseCuid("Demo Burpee Box Jump Over"),
  boxJump: exerciseCuid("Demo Box Jump"),
  boxStepUp: exerciseCuid("Demo Box Step Up"),
  walkingLunge: exerciseCuid("Demo Walking Lunge"),
  sitUp: exerciseCuid("Demo Sit-up"),
  vUp: exerciseCuid("Demo V-up"),
  hollowHold: exerciseCuid("Demo Hollow Hold"),
  plankHold: exerciseCuid("Demo Plank Hold"),
  sidePlankHold: exerciseCuid("Demo Side Plank Hold"),
  lSitHold: exerciseCuid("Demo L-sit Hold"),
  ringRow: exerciseCuid("Demo Ring Row"),
  strictRingPullUp: exerciseCuid("Demo Strict Ring Pull-up"),
  ringMuscleUp: exerciseCuid("Demo Ring Muscle-up"),
  ringDip: exerciseCuid("Demo Ring Dip"),
  barDip: exerciseCuid("Demo Bar Dip"),
  ropeClimb: exerciseCuid("Demo Rope Climb"),
  doubleUnder: exerciseCuid("Demo Double Under"),
  singleUnder: exerciseCuid("Demo Single Under"),
  run: exerciseCuid("Demo Run"),
  shuttleRun: exerciseCuid("Demo Shuttle Run"),
  sprint: exerciseCuid("Demo Sprint"),
  rowErg: exerciseCuid("Demo Row Erg"),
  rowCal: exerciseCuid("Demo Row Erg (calories)"),
  skiErg: exerciseCuid("Demo Ski Erg"),
  skiCal: exerciseCuid("Demo Ski Erg (calories)"),
  bikeErgCal: exerciseCuid("Demo Assault Bike (calories)"),
  bikeErgMin: exerciseCuid("Demo Assault Bike Minutes"),
  atlasStoneToShoulder: exerciseCuid("Demo Atlas Stone to Shoulder"),
  atlasStoneOver: exerciseCuid("Demo Atlas Stone Over"),
  yokeCarry: exerciseCuid("Demo Yoke Carry"),
  sledPush: exerciseCuid("Demo Sled Push"),
  sledPull: exerciseCuid("Demo Sled Pull"),
  bandPullApart: exerciseCuid("Demo Band Pull Apart"),
  bandRow: exerciseCuid("Demo Band Row"),
  bandBicepCurl: exerciseCuid("Demo Band Bicep Curl"),
  bandTricepPushdown: exerciseCuid("Demo Band Tricep Pushdown"),
  boxPistol: exerciseCuid("Demo Box Pistol Squat"),
  sofaStepUp: exerciseCuid("Demo Sofa Step Up"),
  russianTwist: exerciseCuid("Demo Russian Twist"),
  ghdSitUp: exerciseCuid("Demo GHD Sit-up"),
  ghdBackExtension: exerciseCuid("Demo GHD Back Extension"),
  thrusterPullUp: exerciseCuid("Demo Thruster + Pull-up Complex"),
  cleanJerkComplex: exerciseCuid("Demo Clean + Jerk Complex"),
  dbPressPushPress: exerciseCuid("Demo DB Press + Push Press"),
  strictPressPushPress: exerciseCuid("Demo Strict Press + Push Press"),
  dtComplex: exerciseCuid("Demo DT (Deadlift + Hang Clean + Push Jerk)"),
  pullUpOrRingRow: exerciseCuid("Demo Pull-up OR Ring Row"),
  backSquatOrGoblet: exerciseCuid("Demo Back Squat OR Goblet Squat"),
  placeholderBicepsTriceps: exerciseCuid("Demo Placeholder Biceps / Triceps"),
  placeholderCoachChoice: exerciseCuid("Demo Placeholder Coach Choice"),
  placeholderAbs: exerciseCuid("Demo Placeholder Abs"),
  placeholderShoulderAccessory: exerciseCuid("Demo Placeholder Shoulder Accessory"),
  placeholderWarmUp: exerciseCuid("Demo Placeholder Warm Up"),
} as const;

export const LBL = {
  restDay: "demo-rest-day",
  main: "demo-main",
  firstSession: "demo-1st-session",
  secondSession: "demo-2nd-session",
  strength: "demo-strength",
  metcon: "demo-metcon",
  conditioning: "demo-conditioning",
  endurance: "demo-endurance",
  pump: "demo-pump",
  gymnastics: "demo-gymnastics",
  skill: "demo-skill",
  olympic: "demo-olympic",
  accessory: "demo-accessory",
  partner: "demo-partner",
  strengthEndurance: "demo-strength-endurance",
  easyPace: "demo-easy-pace",
  warmUpFeet: "demo-warm-up-feet",
  warmUpRun: "demo-warm-up-run",
  core: "demo-core",
  practice: "demo-practice",
  coolDown: "demo-cool-down",
  mobility: "demo-mobility",
} as const;
