import type { CanonicalDay, CanonicalSession } from "../canonical-schema";

import { LBL } from "./refs";
import {
  BLOCK_ALTERNATING_SETS_WK2_TUE,
  BLOCK_NESTED_COMPOSITE_OVER_LADDER_WK2_TUE,
  BLOCK_NESTED_OVER_PARALLEL_LADDER_WK2_TUE,
  BLOCK_NESTED_ROUNDS_OVER_ROUNDS_WK2_TUE,
  BLOCK_PARALLEL_PYRAMIDS_WK2_TUE,
  BLOCK_PULL_UPS_DIPS_CYCLE_WK2_TUE,
  BLOCK_TIME_WINDOW_OUTER_WK2_TUE,
} from "./week-2-tuesday-archetypes";
import {
  BLOCK_COMPOUND_ROWS_WK2_TUE,
  BLOCK_FOOTNOTES_WK2_TUE,
  BLOCK_IMPLICIT_LABEL_WK2_TUE,
} from "./week-2-tuesday-compounds";

const SESSION_WK2_TUE: CanonicalSession = {
  order: 1,
  label: LBL.firstSession,
  notes: null,
  freezeLoadsAtCreation: false,
  blocks: [
    BLOCK_ALTERNATING_SETS_WK2_TUE,
    BLOCK_NESTED_ROUNDS_OVER_ROUNDS_WK2_TUE,
    BLOCK_NESTED_OVER_PARALLEL_LADDER_WK2_TUE,
    BLOCK_NESTED_COMPOSITE_OVER_LADDER_WK2_TUE,
    BLOCK_TIME_WINDOW_OUTER_WK2_TUE,
    BLOCK_PULL_UPS_DIPS_CYCLE_WK2_TUE,
    BLOCK_PARALLEL_PYRAMIDS_WK2_TUE,
    BLOCK_COMPOUND_ROWS_WK2_TUE,
    BLOCK_FOOTNOTES_WK2_TUE,
    BLOCK_IMPLICIT_LABEL_WK2_TUE,
  ],
};

export const DAY_WK2_TUE: CanonicalDay = {
  dayOfWeek: "TUESDAY",
  label: null,
  notes: null,
  sessions: [SESSION_WK2_TUE],
};
