export const RETENTION_INVITE_TOKEN_TTL_DAYS = 30;
export const RETENTION_ACTION_ITEM_TTL_DAYS = 90;
export const RETENTION_MARKETING_SUBMISSION_TTL_DAYS = 30;

export const MS_PER_DAY = 24 * 60 * 60 * 1000;
